apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-api
  template:
    metadata:
      labels:
        app: demo-api
    spec:
      containers:
        - name: demo-api
          image: {{ .Values.container_registry }}/demo-api:latest
          ports:
            - containerPort: 8080
          env:
            - name: CUBE_PATH
              value: /mnt/data/cube.bin
          volumeMounts:
            - name: blob01
              mountPath: "/mnt/data"
              readOnly: false
      volumes:
        - name: blob01
          persistentVolumeClaim:
            claimName: pvc-blob
