apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-api
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        app: demo-api
    spec:
      containers:
        - name: demo-api
          image: {{ .Values.container_registry }}{{ .Values.api.image.name }}:{{ .Values.api.image.tag }}
          ports:
            - containerPort: 8080
          env:
            - name: CUBE_ROOT_DIR
              value: /mnt/data
          volumeMounts:
            - name: blob01
              mountPath: "/mnt/data"
              readOnly: false
      volumes:
        - name: blob01
          persistentVolumeClaim:
            claimName: pvc-blob
