apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-managed-disk
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: managed-csi-premium
  resources:
    requests:
      storage: 20Gi
