{{- if .Values.blobfuse }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-blob
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 2Gi
  volumeName: pv-blob
  storageClassName: azureblob-fuse-premium
{{- end }}