apiVersion: v1
kind: Secret
metadata:
  name: storage-account-secret
type: Opaque
data:
  azurestorageaccountname: {{ .Values.storage_account.name | b64enc | quote }}
  azurestorageaccountkey: {{ .Values.storage_account.key | b64enc | quote }}
