name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_REGISTRY_URL }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build Docker image
      run: docker build -t demo-api .
      #working-directory: ./demo-pv-performance

    - name: Tag Docker image
      run: docker tag demo-api ${{ secrets.ACR_REGISTRY_URL }}/demo-api:${{ github.sha }}

    - name: Push Docker image to Azure Container Registry
      run: docker push ${{ secrets.ACR_REGISTRY_URL }}/demo-api:${{ github.sha }}
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Install Helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - name: AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ secrets.AKS_RG }}
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}
#      - name: Azure AKS Set Context
#        uses: azure/aks-set-context@v1
#        with:
#          creds: ${{ secrets.AKS_SP_CLIENT_SECRET }}
#          cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}
#          resource-group: ${{ secrets.AKS_RG }}
#          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Helm upgrade
        run: |
          helm upgrade --install demo-pv-performance ./helm --set image.tag=${{ github.sha }}
